# Generated by Django 4.2.30 on 2026-09-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='หมายเลขโต๊ะ')),
                ('seats', models.PositiveIntegerField(default=4, verbose_name='จำนวนที่นั่ง')),
                ('status', models.CharField(choices=[('empty', 'ว่าง'), ('occupied', 'มีลูกค้า'), ('billing', 'รอเช็คบิล')], default='empty', max_length=20, verbose_name='สถานะ')),
            ],
            options={
                'verbose_name': 'โต๊ะ',
                'verbose_name_plural': 'โต๊ะ',
                'ordering': ['number'],
            },
        ),
    ]
