# Generated by Django 4.2.30 on 2026-09-28 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='หมวดหมู่')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งาน')),
            ],
            options={
                'verbose_name': 'หมวดหมู่',
                'verbose_name_plural': 'หมวดหมู่',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='ชื่อเมนู')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคา')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_images/', verbose_name='รูปภาพ')),
                ('status', models.CharField(choices=[('available', 'พร้อมขาย'), ('sold_out', 'หมด')], default='available', max_length=20, verbose_name='สถานะ')),
                ('is_active', models.BooleanField(default=True, verbose_name='แสดงเมนู')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.category', verbose_name='หมวดหมู่')),
            ],
            options={
                'verbose_name': 'เมนู',
                'verbose_name_plural': 'เมนู',
            },
        ),
    ]
