# Generated by Django 4.2.30 on 2026-09-28 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'เปิดอยู่'), ('cooking', 'กำลังทำ'), ('served', 'เสิร์ฟแล้ว'), ('paid', 'ชำระแล้ว'), ('cancelled', 'ยกเลิก')], default='open', max_length=20, verbose_name='สถานะ')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tables.table', verbose_name='โต๊ะ')),
            ],
            options={
                'verbose_name': 'ออเดอร์',
                'verbose_name_plural': 'ออเดอร์',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='จำนวน')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาต่อหน่วย')),
                ('status', models.CharField(choices=[('pending', 'รอดำเนินการ'), ('cooking', 'กำลังทำ'), ('done', 'เสร็จ'), ('cancelled', 'ยกเลิก')], default='pending', max_length=20, verbose_name='สถานะ')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menus.menuitem', verbose_name='เมนู')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'verbose_name': 'รายการอาหาร',
                'verbose_name_plural': 'รายการอาหาร',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ยอดก่อนคิด')),
                ('service_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ค่าบริการ')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ภาษี')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ส่วนลด')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ยอดสุทธิ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='orders.order', verbose_name='ออเดอร์')),
            ],
            options={
                'verbose_name': 'บิล',
                'verbose_name_plural': 'บิล',
            },
        ),
    ]
